### PR TITLE
[5.x] Update 5.4.1 Magnes Pt 2

### PR DESCRIPTION
**Pull request by jaxdesmarais**
### Summary of changes

- The versions somehow got goofed in the last PR, no idea what version of Magnes we linked since they don't contain the version anywhere, this is actually 5.4.1 with staging removed
- Can be verified by pulling down this branch and running the following:
    - Navigate to `Frameworks/XCFrameworks/PPRiskMagnes.xcframework/ios-arm64_x86_64-simulator/PPRiskMagnes.framework` and `Frameworks/XCFrameworks/PPRiskMagnes.xcframework/ios-arm64/PPRiskMagnes.framework`
    - Run `strings PPRiskMagnes | grep "stage"`
    - Nothing should be returned
- The command `strings PPRiskMagnes | grep "stage"` can also be run for the version linked for Carthage at `https://assets.braintreegateway.com/mobile/ios/carthage-frameworks/pp-risk-magnes/PPRiskMagnes.json` for version `5.4.1-stage-removed`

### Checklist

- [x] Added a changelog entry

### Authors

- @jaxdesmarais

### CODE REVIEW

**Comment by jaxdesmarais** [comment]
I think these failures make sense compatibility wise, will circle back with the Magnes team on these

**Review by scannillo — APPROVED** [review]

**Comment by jaxdesmarais** [comment]
Will update this PR with the carthage version once that is released

**Comment by jaxdesmarais** [comment]
Carthage cache is still only sometimes working - escalating internally to see why the cache for our assets is so flakey suddenly

**Comment by jaxdesmarais** [comment]
UI test failure is unrelated to this PR. Assets have been stable for 24 hours so we should be good to merge this in.

**Pull request merged**
