### PR TITLE
SPM Analytics Metadata

### PR DESCRIPTION
**Pull request by scannillo**
### Summary
Add Analytics metadata for if Swift Package Manager is used.

### Note
It would be nice to have an `iosPackageManager` field that returns a string `CocoaPods`, `Swift Package Manager`, or `Carthage`. However, there is no way to differentiate between a Carthage integration & a manual integration. 

We could leave as-is, or instead have an `iosPackageManager` field with the options of:
- `CocoaPods`
- `Swift Package Manager`
- `Carthage or Manual integration`

### Checklist

- ~Added a changelog entry~

### CODE REVIEW

**Comment by sestevens** [comment]
I think we should have one field with three possible values: `cocoapods`, `spm`, `carthage/manual`. Just my 2 cents!

**Comment by scannillo** [comment]
> @sestevens  I think we should have one field with three possible values: cocoapods, spm, carthage/manual. Just my 2 cents!

I am down for that. 

Do we think somewhere/someone at BT is using `iosIsCocoaPods` and that our removing it would break anything? The only scenario I can think of is people's SUMO searches.

**Comment by sestevens** [comment]
Hmm... I'd be surprised if removing that field broke anything.

**Comment by scannillo** [comment]
Update made 👍 . We couldn't find a way to have a unit test test for each package string returned. We did manually test in our SPM sample app and saw the correct value.

**Review by sestevens — APPROVED** [review]
Looks good to me!

**Review by sshropshire — APPROVED** [review]

**Pull request merged**
