### PR TITLE
Xcode 7 beta support

### PR DESCRIPTION
**Pull request by mickeyreiss**
I'll use this pull request to track Xcode 7 beta support.

Our general plan is this:
* Support Xcode 6/iOS 8.4 on our `master` branch
* Support Xcode 7 beta/iOS 9 (along with Swift 2.0) on our `xcode-beta` branch
* Iterate on our Swift interface as Swift 2.0 is finalized over the next few months
* Merge (likely `git merge --squash`) `xcode-beta` into `master` when the Xcode 7 GM seed is released
  * Drop support for Xcode 6
  * Continue to support a deployment target as far back as iOS 7

As always, we're open to feedback and suggestions. Thanks!

### CODE REVIEW

**Comment by mickeyreiss** [comment]
We'll also need to address the `canOpenURL:` whitelisting changes. It will probably make sense to do this after the next beta is released—hopefully the acceptable behavior will be clearer at that point.

**Comment by mickeyreiss** [comment]
Another known issue: Closed source components need to support bitcode ([PayPal](https://github.com/paypal/PayPal-iOS-SDK/issues/284) and Kount (`DeviceCollectorSDK`).

**Comment by remzr7** [comment]
Has bit code been enabled on PayPal and Kount yet?

**Comment by burnto** [comment]
@remzr7 not yet.

**Comment by keith** [comment]
Xcode 7 beta 4 started capitalizing nullability annotations:

> The double-underscored nullability qualifiers (__nullable, __nonnull, and __null_unspecified) have
been renamed to use a single underscore with a capital letter (_Nullable, _Nonnull,
and _Null_unspecified, respectively). The compiler predefines macros mapping from the old double underscored names to the new names for source compatibility.

**Comment by intelliot** [comment]
@keith Thanks for pointing that out! The double-underscored nullability qualifiers still work, so we'll continue using them for now.

**Comment by skunkworks** [comment]
To expand on @intelliot 's point, to support both Xcode 6 and 7 simultaneously, we must continue to use the double-underscore nullability annotation format.

**Pull request merged**
