### PR TITLE
Drops iOS 8 deployment target

### PR DESCRIPTION
**Pull request by JackoPlane**
Thank you for your contribution to Braintree. 

> Before submitting this PR, note we cannot accept language translation PRs. We support the same languages that are supported by PayPal, and have a dedicated localization team to provide the translations. If there is an error in a specific translation, you may open an issue and we will escalate it to the localization team.

### Summary of changes

- Set the minimum deployment target to iOS 9, This is required for compiling with Xcode 12

### Checklist

- [x] Added a changelog entry

- @JackoPlane

### CODE REVIEW

**Comment by scannillo** [comment]
Hi @JackoPlane - thank you for opening this PR. We understand that Xcode 12 drops support for iOS 8. 

We will be including this change in our future major version bump (v5) release of `braintree_ios`.

**Comment by eseay** [comment]
@scannillo Can you provide any information on a timeline for that v5 release?

**Comment by scannillo** [comment]
Hi @eseay - we are still working on the v5 updates they should be complete in the coming weeks. We can wait to close this PR until that release goes out.

However - you should have no problem running v4 of our SDK with Xcode 12. As long as your application has a deployment target that is higher than iOS 8, everything should work fine. You might see an[ Xcode warning](https://developers.braintreepayments.com/start/hello-client/ios/v4#using-cocoapods), but everything should work fine as-is for now.

**Comment by sestevens** [comment]
Hi @JackoPlane, we just released a [beta version](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of the SDK that updates the minimum deployment target to iOS 12.

I'm going to close this PR in favor of this new release. Thank you for taking the time to open it!

**Pull request closed without merging**
