### PR TITLE
Update Cocoapods to v1.11 & Gem cleanup

### PR DESCRIPTION
**Pull request by scannillo**
### Summary of changes

- To triage this [GH issue](https://github.com/braintree/braintree_ios/issues/756), we need to be testing with the latest CocoaPods (v1.11)
- This PR updates:
    - `cocoapods` to v1.11.2
    - `jazzy` to v0.14.1 (has a dependency on `cocoapods`)
    - `bundler` to 2.2.31
- Remove unneeded `.ruby-gemset` file from 8 years ago

### Checklist

- ~Added a changelog entry~

### Authors
@scannillo @sshropshire

### CODE REVIEW

**Review by sshropshire — APPROVED** [review]

**Comment by scannillo** [comment]
TODO: we should make sure our GH Actions scripts are using the version of `cocoapods` from our Gemfile. Right now, they aren't.

**Comment by scannillo** [comment]
What is the `.ruby-gemset` file in this repo? It hasn't been touched in 8 years, we can probably delete it.

**Comment by scannillo** [comment]
> TODO: we should make sure our GH Actions scripts are using the version of cocoapods from our Gemfile. Right now, they aren't.

We can leave as is, since GH Actions is pulling in the latest CocoaPods version (+ bundle install takes forever and will slow our CI :D)

**Review by sarahkoop — APPROVED** [review]
Dependency changes look good to me. Approving assuming that UI test failure is a flake?

**Comment by scannillo** [comment]
@sarahkoop - yep. Re-ran CI and that UI test was a flake, because now a different one is failing. Locally, tests are fine. 

I thought we resolved those issues, but we'll have to take another look.

**Pull request merged**
