### PR TITLE
Declare as static variables

### PR DESCRIPTION
**Pull request by chuganzy**
As titled.

### CODE REVIEW

**Comment by demerino** [comment]
Thanks for submitting the PR! Can to add any background information on why this change is required?

I also wanted to mention that additional work on `BraintreeUI` (beyond bug fixes) has been suspended in favor of moving towards our `new Drop-In`: https://github.com/braintree/braintree-ios-drop-in

**Comment by chuganzy** [comment]
> Can to add any background information on why this change is required?

These variables are not exported in header file but linkable which means we cannot define variables with same name. For example, if we define `formFieldTopMargin` with same way, it causes a compile error. We shouldn't make these variables likable so added `static` keyword.
If we want to export them, we should rename them to more unique ones.

> I also wanted to mention that additional work on BraintreeUI (beyond bug fixes) has been suspended in favor of moving towards our new Drop-In: https://github.com/braintree/braintree-ios-drop-in

Oh, I didn't know that!

**Comment by demerino** [comment]
Got it. Thanks for the info.

It is unofficially deprecated (we haven't explicitly deprecated it in the code yet). We've updated our official docs to use the New Drop-In: https://developers.braintreepayments.com/guides/drop-in/ios/v4

**Comment by skunkworks** [comment]
👍

**Pull request merged**
