### PR TITLE
IMPROVEMENT - Added c header search path in Package.swift

### PR DESCRIPTION
**Pull request by kabirkhaan**
Thank you for your contribution to Braintree. 

> Before submitting this PR, note we cannot accept language translation PRs. We support the same languages that are supported by PayPal, and have a dedicated localization team to provide the translations. If there is an error in a specific translation, you may open an issue and we will escalate it to the localization team.

### Summary of changes
During working with [tuist](https://tuist.io) we found a 🐞 regarding the header search path with SPM Brain tree dependency 

Using `BrainTree SPM` package and run `tuist test` will throw the following error

Import headrs are release 
Screenshot 2022-08-11 at 10 45 16

Reason behind this is `tuist generate` and `tuist test` create different graphs for project as per following table. 
Due to different structure of `tuist test`  all file that impot`../BraintreeCore{ANY_CLASS}.h`  will not found.

| `tuist generate` | `tuist test`
| :---: | :---: | 
| Screenshot 2022-08-11 at 23 29 39 | Screenshot 2022-08-11 at 23 28 25 |

from the [tuist test](https://docs.tuist.io/commands/test/)
> Tuist also automatically caches successful test runs - this means that the subsequent tuist test calls will test only what has changed! You will see which test targets are skipped in the log. This is extremely useful especially on CI - if you make a simple change in a module that other targets do not depend on, CI can test only this module and nothing else.

# CHANGELOG

- Remove `#import "../BraintreeCore/{ANY_CLASS}.h`
- Use Same header for Carthage and SPM 
- To resolve the headers use added following in Package.swift
```
cSettings: [
                .headerSearchPath("../")
            ]
``` 

### Checklist

- [x] Added a changelog entry

- @kabirkhaan

### CODE REVIEW

**Comment by mattwylder** [comment]
Hi there! Could you provide more context for the bug you were experiencing with tuist?

Also, we have fixed an issue with GitHub actions that was caused the builds to fail. Can you pull the latest from `master` into your branch?

**Comment by kabirkhaan** [comment]
> Hi there! Could you provide more context for the bug you were experiencing with tuist?
> 
> Also, we have fixed an issue with GitHub actions that was causing the builds to fail. Can you pull the latest from `master` into your branch?


Thanks for the comments and fixing the GitHub action for fork branches 👍 
I update the PR description and put more details.

**Comment by kabirkhaan** [comment]
> Hi there! Could you provide more context for the bug you were experiencing with tuist?
> 
> Also, we have fixed an issue with GitHub actions that was causing the builds to fail. Can you pull the latest from `master` into your branch?

Hello @mattwylder seems like we still have issue with CI with the [line](https://github.com/braintree/braintree_ios/blob/c41fb40d8d5bb7287647c26a5a7ff180b069956c/.github/workflows/build.yml#L122) and[line](https://github.com/braintree/braintree_ios/blob/c41fb40d8d5bb7287647c26a5a7ff180b069956c/.github/workflows/build.yml#L60) 😢

**Comment by mattwylder** [comment]
Hey there! Thanks for your patience. The issue was with the slash in the branch name. We've pushed some changes to `master` that should fix the issue. Can you merge the lastest from `master` into your branch so we run CI?

**Comment by jaxdesmarais** [comment]
Hello @kabirkhaan -

I'd like to take a step back here as the root of the problem seems to be a difference in configuration with how `tuist generate` and `tuist test` create graphs for projects based on this comment in the PR description:

> Reason behind this is tuist generate and tuist test create different graphs for project as per following table.
Due to different structure of tuist test all file that impot../BraintreeCore{ANY_CLASS}.h will not found.

Is there a specific reason why this change resolves the packages as expected with `tuist generate` and `tuist test`? The line running into the error you are seeing is this import:
```
#import "../BraintreeCore/BTAPIClient_Internal.h"
```

The change in this PR prepends `../` to the path:
```
#import <BraintreeCore/BTAPIClient_Internal.h>
```
Which should result in the path now being the same as the previously used `../BraintreeCore/BTAPIClient_Internal.h`.

Additionally, are you able to provide a sample project with this branch pulled in that runs both `tuist generate` and `tuist test` successfully? We aren't familiar with this external dependency so would be helpful to see the difference with running off of your branch vs otherwise.

**Comment by kabirkhaan** [comment]
Hello @jaxdesmarais, Can you please help me if I am missing any context that will help review the PR?

**Comment by jaxdesmarais** [comment]
Hello @kabirkhaan -

Thanks for reaching back out and providing all of those details. At this time we support integrating through Swift Package Manager, CocoaPods, and Carthage and do not officially support `tuist`. At this time, we want to gauge interest in supporting `tuist` before picking up adding this to the SDK. Would you mind opening a [feature request via our GitHub issues](https://github.com/braintree/braintree_ios/issues/new/choose)? This will allow us to track interest in supporting `tuist` officially throughout the community.

**Pull request closed without merging**
