### PR TITLE
Remove invalid excludes from Package.swift

### PR DESCRIPTION
**Pull request by JonathanDowning**
Thank you for your contribution to Braintree. 

> Before submitting this PR, note we cannot accept language translation PRs. We support the same languages that are supported by PayPal, and have a dedicated localization team to provide the translations. If there is an error in a specific translation, you may open an issue and we will escalate it to the localization team.

### Summary of changes

Xcode 13 now shows issues with packages in the issue navigator.
A few issues popped up for this SDK, namely that there is are invalid excludes in the Package.swift, this PR removes them.

### Checklist

- [x] Added a changelog entry

@JonathanDowning

### CODE REVIEW

**Comment by sarahkoop** [comment]
Hi @JonathanDowning - thanks for opening this PR. We are looking into this and will get back to you.

**Comment by scannillo** [comment]
👋  Hey @JonathanDowning  - we will get this fix out in our next release!

**Comment by scannillo** [comment]
Hi @JonathanDowning - this fix was release in [v5.4.2 of Braintree.](https://github.com/braintree/braintree_ios/releases/tag/5.4.2) 

Thanks for opening this PR!

**Comment by JonathanDowning** [comment]
Thank you!

**Pull request closed without merging**
